### PR TITLE
Add perk ref C

### PR DESCRIPTION
**Pull request by marco-palumbi**
This pull request adds PERK pure C implementation for all NIST levels.

Implementation is based on the sources from version v1.1 of 2023/10/16
https://pqc-perk.org/

only differences are:
- include `randombytes.h` instead of `rng.h`
- use `size_t` instead of `unsigned long long` for the api functions
- implementation of the signature parsing for the short parameters using `tinybn` instead of `gmp`

Implementation has been verified locally against the KAT vectors in the v1.1 package

This implementation has no more external dependencies but still uses XKCP from the original package.

### CODE REVIEW

**Comment by marco-palumbi** [comment]
@mkannwischer I left the origina XKCP based implementation for the symmetric functions. This is to have the sources as close as possible to the reference implementation.

I didn't edit the skiplist in pqm4... none of this run on  my stm32f4discovery board because of the memory and may be also the XKCP implementation may give some problem running on the m4.

If the main purpose of this implementation is to produce vectors for the vector test, then I suggest to keep it as is.
If you think it is better if we can run some also on the m4 (with more than 128k memory) then I can integrate the fips202 from the pqm4/mupq.

**Comment by rpls** [comment]
Please excuse the long delay. I've looked through this, and I'm trying to get it to run. For me at least, it doesn't finish the test runs, even on the very fast emulator. A had a very quick glance, and it seems the Keccak code does have an unaligned access when absorbing data, which crashes both emulator and platform.

That doesn't really matter, since I'm not going to merge it with the Keccak code. Please use the functions in the `fips202.h` header. It's just better to keep all schemes comparable (this way, all implementations get a fully optimized Keccak/AES/...). And the C reference implementations aren't just there to generate testvectors on the host, they also give us an idea on how much faster a platform-specific optimized (e.g., M4) version is compared to a portable version. I haven't looked at all your code, but it seems you only have to adapt the `symmetric.{c,h}`.

Aside from that: please use symlinks wherever possible. As a reference, look how we use them in other schemes. Most implementations have identical files, except some configuration headers. Use this approach here as well.

**Comment by marco-palumbi** [comment]
Hi @rpls, 
yes, as you reported the code was not suitable for working on the M4 device as I stated in my comment.
I updated it according with your request along with the use of symlinks.
Some of the scheme versions will not run even in the 4MB RAM emulator... but still run in the host to provide vectors to the m4 implementation.
I didn't update the skip-list...

let me know if you want me do anything else

**Comment by rpls** [comment]
> Some of the scheme versions will not run even in the 4MB RAM emulator... but still run in the host to provide vectors to the m4 implementation.

The `perk-256-short-{3,5}` fail the stack test on my side, is that right?

> I didn't update the skip-list...

I'll merge it with an updated list.

Everything looks good to me now! I'll merge.

**Comment by marco-palumbi** [comment]
Thanks @rpls.
> The `perk-256-short-{3,5}` fail the stack test on my side, is that right?

yes `perk-256-short-{3,5}` needs more than 5 MB of RAM

**Pull request merged**
