### PR TITLE
Add SPHINCS-alpha

### PR DESCRIPTION
**Pull request by mkannwischer**
https://github.com/mupq/pqm4/issues/292

This adds the SPHINCS-alpha implementations from https://csrc.nist.gov/csrc/media/Projects/pqc-dig-sig/documents/round-1/submission-pkg/SPHINCS-ALPHA-submission.zip

Had to make some changes to the `hash_sha2.c`, `hash_shake.c`, `thash_sha2_simple.c`, `thash_shake_simple.c` to use the mupq APIs. 
There are some VLAs that one may want to eliminate later. 
Also these implementations are using insane amounts of RAM. Did not look into why.

### CODE REVIEW

**Comment by rpls** [comment]
Looks like only the `params.h` file differ between all the variants (and separate `{sha2,shake}_offsets.h` and `thash_{sha2,shake}_simple.c` files between the SHA2/SHAKE variants). So I'd prefer symlinks. Aside from that, I'm running the tests.

**Comment by rpls** [comment]
So I looked into why they use such a large amount of BSS, and I think it's somewhat relevant to benchmarking:

https://github.com/mupq/mupq/blob/94cf833955d5687ca7b45b822a8fee8fc0dae27f/crypto_sign/sphincs-a-sha2-128f/ref/wots.c#L47-L64

The `encode` function essentially creates a LUT the first time it's called. Another thing I would have forgotten to look at when searching for statically allocated memory: static variables in functions. I'm not sure how long the LUT generation takes, but the time won't show up in subsequent calls to the scheme.

**Comment by rpls** [comment]
Test and Testvectors work on the board, but as for SNOVA, let's talk about the LUTs.

**Comment by mkannwischer** [comment]
> Looks like only the `params.h` file differ between all the variants (and separate `{sha2,shake}_offsets.h` and `thash_{sha2,shake}_simple.c` files between the SHA2/SHAKE variants). So I'd prefer symlinks. Aside from that, I'm running the tests.

Agreed. I changed it to symlinks.

**Comment by mkannwischer** [comment]
> So I looked into why they use such a large amount of BSS, and I think it's somewhat relevant to benchmarking:
> 
> https://github.com/mupq/mupq/blob/94cf833955d5687ca7b45b822a8fee8fc0dae27f/crypto_sign/sphincs-a-sha2-128f/ref/wots.c#L47-L64
> 
> The `encode` function essentially creates a LUT the first time it's called. Another thing I would have forgotten to look at when searching for statically allocated memory: static variables in functions. I'm not sure how long the LUT generation takes, but the time won't show up in subsequent calls to the scheme.

Unfortunately that part is crazily expensive. The first call (for sphincs-a-sha2-128f)  takes 14829169 cycles, while subsequent calls only take 50000 cycles.

**Comment by mkannwischer** [comment]
I pulled that precomputation out of the leaf function and put the memory into the core functions. So I think now we have fair benchmarks, although they may want to re-think if this is the best way to do it.

**Comment by rpls** [comment]
Something is off here. One is the symlinks: you have the `sha2` and the `shake` version, each as a "master copy" (`{sha2,shake}-128f` seems to be the base for each) and then the rest reference to them. I think, most files are still identical except for the `thash_{sha2,shake}` files. And I think you missed, that you symlinked them, because your precomputation patch only changed the `shake` version, not the `sha2` version. Now the bad news: I think your precomputation patch has some error, because the testvector generation fails on my machine (the host-binary failes with "ERROR: signature verification failed"). I'm looking into what might be the problem, because the tests run just fine on QEMU...

**Comment by rpls** [comment]
Could it be, that they assume some of the entries are all zeros? When it was allocated uninitialized to static memory, this is actually the case (lands in the bss section), when it's on the stack, it can be anything.

**Comment by mkannwischer** [comment]
Yes, you are right. I added the symlinks and the init now. Please have another look.

**Pull request merged**
