### PR TITLE
Add MEDS

### PR DESCRIPTION
**Pull request by ilway25**
https://github.com/mupq/pqm4/issues/280

This adds the MEDS implementations from their NIST submission.

Their interface for SHAKE has a slightly different semantics than that provided with mupq (incremental and non-incremental are mixed), so a wrapper is provided.

### CODE REVIEW

**Comment by rpls** [comment]
Two things that should be changed:
- Remove all `fprintf`s from the files. The implementation also has a lot of optional logging, which is turned off, so that's fine. But all the error checks seem to have `fprintf`s everywhere. I'd say, just remove all of them and leave the `return -1;` that follows most places. Alternatively, add an `#ifdef DEGUG` around all the fprintf`s.
- Rename the folder to lowercase `meds*`.

**Comment by ilway25** [comment]
TODO: need to change symlink targets to lower case.

**Comment by mkannwischer** [comment]
`crypto_sign` of the smallest parameter set (meds9923) requires just under a MB of stack space. That's not going to work out.

**Comment by mkannwischer** [comment]
`meds13220` and `meds55604` should work though. Here is the corresponding skiplist:
```
skip_list = [
    {'scheme': 'meds55604', 'implementation': 'ref', 'estmemory': 509952},
    {'scheme': 'meds41711', 'implementation': 'ref', 'estmemory': 1387520},
    {'scheme': 'meds13220', 'implementation': 'ref', 'estmemory': 209920},
    {'scheme': 'meds167717', 'implementation': 'ref', 'estmemory': 927744},
    {'scheme': 'meds134180', 'implementation': 'ref', 'estmemory': 1152000},
    {'scheme': 'meds9923', 'implementation': 'ref', 'estmemory': 1019904},
]
```

**Comment by rpls** [comment]
So I kind of forgot, that I had the MEDS test running on the server... for more than a week. The two implementations that _should_ fit are `meds13220` and `meds55604`, but only the former finished on the platform. The latter appears to get stuck at some point? Everything runs fine in the GDB...

**Comment by mkannwischer** [comment]
I manually ran it for meds55604 on the nucleo-l4r5zi (with NTESTS=1) and the output is looking good to me: 
```
==========================
crypto_sign_keypair DONE.

crypto_sign DONE.

OK Signature did verify correctly!

crypto_sign_open DONE.

crypto_sign_keypair DONE.

crypto_sign_keypair DONE.

crypto_sign DONE.

OK Signature did not verify correctly under wrong public key!

crypto_sign_open DONE.

#
```


So either this is a bug that does not occur all the time (there are some failure cases in keygen, so I would bet on those), or your system is different from mine. Still using gcc 12.3 -- so that could also cause it.
Will run some more tests now.

**Pull request merged**
