### PR TITLE
Add AIMer mem_opt implementations for all NIST security levels

### PR DESCRIPTION
**Pull request by kykypyza3724**
Add AIMer v2.1 mem_opt implementations, tested on necleo-l4r5zi board for all NIST security levels.

### CODE REVIEW

**Comment by mkannwischer** [comment]
Thanks for this PR @kykypyza3724!! I'll test & benchmark this soon so we can merge it. 
Two questions in advance: 
 - Do I understand correctly that this version is not compatible with the old version that was in mupq? 
 - Is it easy to add the reference implementation as well? Then we can test that it's compatible with the memory-optimized version. If it fits within 4 MiB, we can run it on qemu - if not we can still run it on the host.

**Comment by Jhkwon3002** [comment]
Hi, @mkannwischer.
Thank you for your prompt reply.
- The symmetric primitive of the AIMer signature scheme has been updated to AIM2 (https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/jcIEYtrXhPY/m/oRAjoaIxGQAJ). Thus, this version (v2.1) is not compatible with the old version (v1.0) in mupq. 
- We added the reference C implementation of the AIMer v2.1. In our experiment, the "aimer256s" implementation required more than 4 MiB of memory.

**Comment by mkannwischer** [comment]
Great thanks!

**Comment by mkannwischer** [comment]
All works fine for me both on qemu and on the `nucleo-l476rg`. 
I opened https://github.com/mupq/pqm4/pull/350 to pull it into pqm4 - please have a look there and let me know if the benchmarking results look the way you expect them.

Thanks again for your PR @Jhkwon3002.

**Pull request merged**
