### PR TITLE
Add Picnic

### PR DESCRIPTION
**Pull request by mkannwischer**
From https://github.com/dkales/picnic_m4/tree/24c99860e96186a5c9b3b08b6390c7cec6dae242

Only includes the compatible implementations, not the low memory modifications which change testvectors.

### CODE REVIEW

**Review by rpls — COMMENTED** [review]
The `picnic3l1/opt-mem` contains ARM specific code, albeit with an `#ifdef` switching between a generic C variant as far as I can tell. We should discuss whether we want this in `mupq`. I'm ok with this, as long as there's a C alternative that is picked automatically. And in this instance, I would suggest a different `#if{,n}def`, since the code should also work for `pqm3` (haven't tested yet though). Apart from this, the code works on my end.

**Comment by mkannwischer** [comment]
Yes, you are right. We shouldn't have such implementations in mupq. I've moved them to pqm3/pqm4.

**Comment by mkannwischer** [comment]
Can you have another look? 
I will also run some m3 benchmarks and open a PR in pqm3.

**Comment by rpls** [comment]
LGTM. Btw. the falcon opt-ct also contains ARM code.

**Pull request merged**
