### PR TITLE
Add LUOV

### PR DESCRIPTION
**Pull request by Ko-**
This is a first attempt to integrate a `ref` implementation of a single parameter set for LUOV into `pqm4`.

The scheme fits and `testvectors` are matching. However, for some reason `test` fails for me. Apparently `check_canary(sk)` returns an error code. Sometimes.

When I do something like this in `test.c`, I do not get an error anymore and all tests pass.
```c
        else if (check_canary(sk)) {
            hal_send_str("ERROR canary sk start overwritten\n");
            uint64_t val = *(uint64_t *)sk;
            char buf[32];
            sprintf(buf, "sk start: %08llx\n", val);
            hal_send_str(buf);
        }
```

I don't immediately see what's wrong. `sk` is filled with 32 random bytes in keygen and then used as input to SHAKE in keygen and signing.

I'm parking this here for now.

### CODE REVIEW

**Comment by mkannwischer** [comment]
Did you try valgrind/asan on the host?

**Comment by Ko-** [comment]
I did on the `testvectors` binary. Valgrind doesn't report anything with `memcheck` (although it would never detect stack buffer overruns) nor with `exp-sgcheck`. I also tried compiling with `-fsanitize=address -lasan` but that didn't report anything either.

**Comment by thomwiggers** [comment]
FYI: there's also `-fsanitize=memory` and `-fsanitize=undefined`, which all do different things. Might be worth quickly trying.

**Comment by Ko-** [comment]
`-fsanitize=undefined` doesn't report anything, `-fsanitize=memory` doesn't exist for gcc 8.3.0.

**Comment by Ko-** [comment]
I solved the issue with failing tests and I added the other parameter sets. At first sight it looks like `luov-48-43-222-*`, `luov-64-61-302-*`, and `luov-8-58-237-*` work, but `luov-80-76-363-*`, `luov-8-82-323-*`, and `luov-8-107-371-*` might be too big. Or I'm not patient enough. I'll try to run benchmarks tomorrow.

**Pull request merged**
