### PR TITLE
BIKE round4

### PR DESCRIPTION
**Pull request by 37eex9**
As mentioned [here](https://github.com/mupq/pqm4/issues/251) the current BIKE implementation is outdated.
This pull request should fix it and update the BIKE schemes to specification v5.1, which is the version submitted for round 4.
* I verified the changes with KATs. The code I used to generate KAT output with the mupq repo can be found in my branch [nist-kat](https://github.com/37eex9/mupq/tree/nist-kat). However, this branch does not implement v.5.1.
* I made minor changes to reduce the compiler warnings for testvector compilation.
* I fixed a typo to make testvectors (and possibly other python scripts) work with ChipWhisperer targets, as mentioned in issue #116

### CODE REVIEW

**Comment by rpls** [comment]
I can test this soon. But some questions/comments upfront:

- Why the change to the `testvectors.c`?
- Do you know anything about the ARM Implementation in PQM4? Is it completely obsolete, or is there also an update? Or does this one replace it completely?
- On second look, there is some CCM specific stuff in there, does the Implementation explicitly need this (looks like it's optional)?
- Most files are identical between L1/L3, could you please use symlinks wherever possible?

**Comment by 37eex9** [comment]
* The ARM implementation is outdated as well, I already prepared some changes to update this, too. The Cortex-M4 optimization is not affected through the update and should be maintained further, in my opinion.
* Can you specify where you found CCM specific stuff? I could not locate it and already removed some AES related files.
* Nice idea about using symlinks. I just stuck to the way I found it, and there were no symlinks :)

Sorry I messed up with the git history on my branch, I hope no one already cloned it locally. ^^

**Comment by rpls** [comment]
It seems the CCM stuff was only in the `decode.c` file of the L3 variant. Since that's now a symlink to the L1, it's gone. As for the M4 implementation, do you have a timeline on that? If that's too far in the future, we sould probably remove it until an update is available.

**Comment by 37eex9** [comment]
I see the CCM stuff, `decode.c` is one of the few files which is no symlink. I can have a look at this in next few days. The changes in both, mupq and pqm4, are very similar and for pqm4 the update can be found in my [fork](https://github.com/37eex9/pqm4/tree/bike-round4). I thought I would be waiting with a pull request after this one is accepted, so the update for pqm4 and pqm4/mupq can be done at once.

**Comment by 37eex9** [comment]
Now I removed unused code from the specified files. I did not test it exhaustively but compiling the targets for different platforms seems to give reasonable binaries and `test.py` and `testvectors.py` were successful with `mps2an-386` qemu platform.
It turned out I was confused about CCM and thought it was related to [AES}](https://en.wikipedia.org/wiki/CCM_mode), but it was about using core coupled memory for `stm32f4` platforms, to make more memory available as RAM. However, there was some code depending on preprocessor flags that were disabled. So, the code could be removed without any effect but reducing the code base.

There are some files that are identical between the pqm4 and the mupq implementations. Does it make sense to use symlinks here, too? My first choice would be, not to use symlinks here to keep independence between the two repositories.

I hope everything is fine now to accept the pull request. =)

**Comment by rpls** [comment]
> There are some files that are identical between the pqm4 and the mupq implementations. Does it make sense to use symlinks here, too? My first choice would be, not to use symlinks here to keep independence between the two repositories.

There are some PQM4 implementations with symlinks to mupq, which IMO is fine. Only the other way around would be bad (since pqm4 depends on mupq, but mupq not on pqm4).

I'll check it out and merge.

**Comment by rpls** [comment]
There seems to be a problem on MacOS when compiling for the host, but I think that's for me to solve in a build system update. I'll merge this as is, but I'll remove the bikel1/3 m4f implementations, since they will now fail the testvector test.

**Pull request merged**
